source 'https://rubygems.org'
ruby "2.3.1"

gem 'rails', '4.2.7.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'friendly_id', github: 'doncote/friendly_id', branch: 'master'
gem 'settingslogic'
gem 'activeadmin', github: 'activeadmin'
gem 'devise'
gem 'cancancan'
gem 'country_select', github: 'stefanpenner/country_select'
gem 'twitter-bootstrap-rails'
gem 'mp3info'
gem 'stamp'
gem 'rake-progressbar'

group :local, :test, :development do
  gem "factory_girl_rails", "~> 4.0"
  gem 'rspec-rails'
  gem 'terminal-notifier-guard'
  gem 'bullet'
  gem "pry"
  gem 'pry-rails'
  gem 'pry-coolline'
  gem 'pry-byebug'
  gem 'awesome_print'
  gem 'spring-commands-rspec'
  gem 'spring'
  gem 'thin'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'faker'
  gem 'shoulda'
  gem 'shoulda-matchers'
  gem 'guard'
  gem 'guard-rspec'
  gem 'timecop'
  gem 'database_cleaner'
end
